# Generated by Django 6.1.1 on 2026-09-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ', models.CharField()),
                ('certificate', models.TextField()),
                ('major', models.TextField()),
                ('score', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
