# Generated by Django 6.1.1 on 2026-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='score',
            field=models.CharField(),
        ),
    ]
