# Generated by Django 6.1.1 on 2026-09-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date',
            field=models.CharField(default='2026-Present', max_length=100),
        ),
    ]
