# Generated by Django 6.1.1 on 2026-09-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='ramtin', max_length=200),
        ),
    ]
